In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df=pd.read_csv("mymoviedb.csv",lineterminator='\n')

In [11]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   str
 1   Title              9827 non-null   str
 2   Overview           9827 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   str
 7   Genre              9827 non-null   str
 8   Poster_Url         9827 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 691.1 KB

By seeing the info of the dataframe we can notice that the release date is in the str format

In [16]:
df['Genre'].head()

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: str

There are blank space in the genre

In [17]:
df.duplicated().sum()

np.int64(0)

To check if any duplicate value is there,there is no duplicate values

In [18]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

basic stats of data

In [8]:
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

summary till now from the data
Data columns (total 9 columns)
1)release date is in str format we want to convert it into datetime
2)no duplicates
3)unwanted blank space in genre
2)remove unwanted columns
The goal is to find
1)what is most frequent genre of movies released on netflix?
2)what genre has the highest votes?
3)which movie got highest popularity and what is its genre?
4)which movie got lowest popularity and what is its genre?
5)which year has a most flimed movies

In [21]:
# dropping unwanted columns
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [25]:
df.drop(columns=["Overview","Original_Language","Poster_Url"],inplace=True)

In [26]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021-12-15,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022-03-01,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022-02-25,No Exit,2618.087,122,6.3,Thriller
3,2021-11-24,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021-12-22,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"

In [28]:
# check for duplictaes
df.duplicated().sum()

np.int64(0)

no duplicate found

In [30]:
df.isnull().sum()

Release_Date     0
Title            9
Popularity      10
Vote_Count      10
Vote_Average    10
Genre           11
dtype: int64

In [37]:
df.columns

Index(['Release_Date', 'Title', 'Popularity', 'Vote_Count', 'Vote_Average',
       'Genre'],
      dtype='str')

In [71]:
df["New"]=r4df['Title'].dropna()

In [74]:
df["New"].isnull().sum()

np.int64(9)

In [75]:
df["Title"]

0                    Spider-Man: No Way Home
1                                 The Batman
2                                    No Exit
3                                    Encanto
4                             The King's Man
                        ...
9832                                Badlands
9833                        Violent Delights
9834                            The Offering
9835    The United States vs. Billie Holiday
9836                                 Threads
Name: Title, Length: 9837, dtype: str

In [62]:
df.isnull().sum()

Release_Date     0
Title            9
Popularity      10
Vote_Count      10
Vote_Average    10
Genre           11
dtype: int64

In [43]:
df['Genre'].head()

0    Action, Adventure, Science Fiction
1              Crime, Mystery, Thriller
2                              Thriller
3    Animation, Comedy, Family, Fantasy
4      Action, Adventure, Thriller, War
Name: Genre, dtype: str

In [68]:
# df[["Vote_Count","Vote_Average"]].astype('int32')

In [67]:
df.tail()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
9832,1973-10-15,Badlands,13.357,896,7.6,"Drama, Crime"
9833,2020-10-01,Violent Delights,13.356,8,3.5,Horror
9834,2016-05-06,The Offering,13.355,94,5.0,"Mystery, Thriller, Horror"
9835,2021-03-31,The United States vs. Billie Holiday,13.354,152,6.7,"Music, Drama, History"
9836,1984-09-23,Threads,13.354,186,7.8,"War, Drama, Science Fiction"

In [76]:
df.isnull().sum().sum()

np.int64(59)